// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnwqxihwdtkxgstkgypu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdud3F4aWh3ZHRreGdzdGtneXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjcyODYsImV4cCI6MjA2NTc0MzI4Nn0.ObySE26zMCeDyG3GzRvz3WeeI00XxBJAcqsDj-_FcNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);